### ISSUE TITLE
Returns ok when compressing an empty binary, but fails on decompression

### ISSUE THREAD

**Issue by pmembrey** [fdmanana/snappy-erlang-nif#6]
Hi guys,

I came across a situation where a user was sending an empty message. `snappy:compress()` would accept it and return `{ok,<<>>}`. However if you try to decompress `<<>>` you get the error message `{error,data_not_compressed}`.

This error message is misleading, because it's not clear whether the data is okay but was stored uncompressed (for whatever reason) or whether the data itself is invalid. According to the C++ version, the data is considered as invalid.

I'm not sure what the best way to handle this situation is. Either it should return an error on compression (say `{error,cant_compress_empty_bytes}`) or on decompression it should just return `{ok,<<>>}`. I guess the first would probably be a better option?

I would also suggest we change `{error,data_not_compressed}` to `{error,not_valid_snappy_compressed_data}` or similar.

Happy to put some code together if you can let me know which direction you want to take...

Cheers,

Pete

**Comment by dch** [comment]
I think we can close this, yes?

**Comment by pmembrey** [comment]
Yes, the PR in  #10 resolved this issue :)
